### ISSUE TITLE
unable to work google format plugin at windows

### ISSUE THREAD

**Issue by northerndeveloper** [Cosium/git-code-format-maven-plugin#60] opened 2020-09-20 12:06 UTC
Hello

Is there a way to work cosium google format plugin at windows machines ? It works properly in UNIX systems but it does not work at Windows Machines ? Do you know the reason behind that ? 

Thank you

**Comment by reda-alaoui** [comment] 2020-09-20 14:27
Duplicate of #59

**Closed by reda-alaoui** 2020-09-20 14:27 UTC
