### ISSUE TITLE
Expose max column length

### ISSUE THREAD

**Issue by Omar-Salem** [Cosium/git-code-format-maven-plugin#138] opened 2023-07-27 23:11 UTC
Is there a way to control max width?

`<googleJavaFormat.maxLineLength>1000</googleJavaFormat.maxLineLength>` does not work

**Comment by reda-alaoui** [comment] 2023-07-28 05:09
Duplicate of https://github.com/Cosium/git-code-format-maven-plugin/issues/76

**Closed by reda-alaoui** 2023-07-28 05:09 UTC
